<?php

declare(strict_types=1);

namespace App\Enums;

enum CountryFlag: string
{
    case Andorra = 'ad';
    case UnitedArabEmirates = 'ae';
    case Afghanistan = 'af';
    case AntiguaAndBarbuda = 'ag';
    case Anguilla = 'ai';
    case Albania = 'al';
    case Armenia = 'am';
    case Angola = 'ao';
    case Antarctica = 'aq';
    case Argentina = 'ar';
    case ArabLeague = 'arab';
    case AmericanSamoa = 'as';
    case Asean = 'asean';
    case Austria = 'at';
    case Australia = 'au';
    case Aruba = 'aw';
    case AlandIslands = 'ax';
    case Azerbaijan = 'az';
    case BosniaAndHerzegovina = 'ba';
    case Barbados = 'bb';
    case Bangladesh = 'bd';
    case Belgium = 'be';
    case BurkinaFaso = 'bf';
    case Bulgaria = 'bg';
    case Bahrain = 'bh';
    case Burundi = 'bi';
    case Benin = 'bj';
    case SaintBarthelemy = 'bl';
    case Bermuda = 'bm';
    case Brunei = 'bn';
    case Bolivia = 'bo';
    case CaribbeanNetherlands = 'bq';
    case Brazil = 'br';
    case Bahamas = 'bs';
    case Bhutan = 'bt';
    case BouvetIsland = 'bv';
    case Botswana = 'bw';
    case Belarus = 'by';
    case Belize = 'bz';
    case Canada = 'ca';
    case CocosIslands = 'cc';
    case CongoDemocraticRepublic = 'cd';
    case CentralEuropeanFreeTradeAgreement = 'cefta';
    case CentralAfricanRepublic = 'cf';
    case CongoRepublic = 'cg';
    case Switzerland = 'ch';
    case IvoryCoast = 'ci';
    case CookIslands = 'ck';
    case Chile = 'cl';
    case Cameroon = 'cm';
    case China = 'cn';
    case Colombia = 'co';
    case ClippertonIsland = 'cp';
    case CostaRica = 'cr';
    case Cuba = 'cu';
    case CapeVerde = 'cv';
    case Curacao = 'cw';
    case ChristmasIsland = 'cx';
    case Cyprus = 'cy';
    case CzechRepublic = 'cz';
    case Germany = 'de';
    case DiegoGarcia = 'dg';
    case Djibouti = 'dj';
    case Denmark = 'dk';
    case Dominica = 'dm';
    case DominicanRepublic = 'do';
    case Algeria = 'dz';
    case EastAfricanCommunity = 'eac';
    case Ecuador = 'ec';
    case Estonia = 'ee';
    case Egypt = 'eg';
    case WesternSahara = 'eh';
    case Eritrea = 'er';
    case Catalonia = 'es-ct';
    case Galicia = 'es-ga';
    case BasqueCountry = 'es-pv';
    case Spain = 'es';
    case Ethiopia = 'et';
    case EuropeanUnion = 'eu';
    case Finland = 'fi';
    case Fiji = 'fj';
    case FalklandIslands = 'fk';
    case Micronesia = 'fm';
    case FaroeIslands = 'fo';
    case France = 'fr';
    case Gabon = 'ga';
    case England = 'gb-eng';
    case NorthernIreland = 'gb-nir';
    case Scotland = 'gb-sct';
    case Wales = 'gb-wls';
    case UnitedKingdom = 'gb';
    case Grenada = 'gd';
    case Georgia = 'ge';
    case FrenchGuiana = 'gf';
    case Guernsey = 'gg';
    case Ghana = 'gh';
    case Gibraltar = 'gi';
    case Greenland = 'gl';
    case Gambia = 'gm';
    case Guinea = 'gn';
    case Guadeloupe = 'gp';
    case EquatorialGuinea = 'gq';
    case Greece = 'gr';
    case SouthGeorgiaAndSouthSandwichIslands = 'gs';
    case Guatemala = 'gt';
    case Guam = 'gu';
    case GuineaBissau = 'gw';
    case Guyana = 'gy';
    case HongKong = 'hk';
    case HeardIslandAndMcDonaldIslands = 'hm';
    case Honduras = 'hn';
    case Croatia = 'hr';
    case Haiti = 'ht';
    case Hungary = 'hu';
    case CanaryIslands = 'ic';
    case Indonesia = 'id';
    case Ireland = 'ie';
    case Israel = 'il';
    case IsleOfMan = 'im';
    case India = 'in';
    case BritishIndianOceanTerritory = 'io';
    case Iraq = 'iq';
    case Iran = 'ir';
    case Iceland = 'is';
    case Italy = 'it';
    case Jersey = 'je';
    case Jamaica = 'jm';
    case Jordan = 'jo';
    case Japan = 'jp';
    case Kenya = 'ke';
    case Kyrgyzstan = 'kg';
    case Cambodia = 'kh';
    case Kiribati = 'ki';
    case Comoros = 'km';
    case SaintKittsAndNevis = 'kn';
    case NorthKorea = 'kp';
    case SouthKorea = 'kr';
    case Kuwait = 'kw';
    case CaymanIslands = 'ky';
    case Kazakhstan = 'kz';
    case Laos = 'la';
    case Lebanon = 'lb';
    case SaintLucia = 'lc';
    case Liechtenstein = 'li';
    case SriLanka = 'lk';
    case Liberia = 'lr';
    case Lesotho = 'ls';
    case Lithuania = 'lt';
    case Luxembourg = 'lu';
    case Latvia = 'lv';
    case Libya = 'ly';
    case Morocco = 'ma';
    case Monaco = 'mc';
    case Moldova = 'md';
    case Montenegro = 'me';
    case SaintMartin = 'mf';
    case Madagascar = 'mg';
    case MarshallIslands = 'mh';
    case NorthMacedonia = 'mk';
    case Mali = 'ml';
    case Myanmar = 'mm';
    case Mongolia = 'mn';
    case Macau = 'mo';
    case NorthernMarianaIslands = 'mp';
    case Martinique = 'mq';
    case Mauritania = 'mr';
    case Montserrat = 'ms';
    case Malta = 'mt';
    case Mauritius = 'mu';
    case Maldives = 'mv';
    case Malawi = 'mw';
    case Mexico = 'mx';
    case Malaysia = 'my';
    case Mozambique = 'mz';
    case Namibia = 'na';
    case NewCaledonia = 'nc';
    case Niger = 'ne';
    case NorfolkIsland = 'nf';
    case Nigeria = 'ng';
    case Nicaragua = 'ni';
    case Netherlands = 'nl';
    case Norway = 'no';
    case Nepal = 'np';
    case Nauru = 'nr';
    case Niue = 'nu';
    case NewZealand = 'nz';
    case Oman = 'om';
    case Panama = 'pa';
    case PacificIslandsForum = 'pc';
    case Peru = 'pe';
    case FrenchPolynesia = 'pf';
    case PapuaNewGuinea = 'pg';
    case Philippines = 'ph';
    case Pakistan = 'pk';
    case Poland = 'pl';
    case SaintPierreAndMiquelon = 'pm';
    case PitcairnIslands = 'pn';
    case PuertoRico = 'pr';
    case Palestine = 'ps';
    case Portugal = 'pt';
    case Palau = 'pw';
    case Paraguay = 'py';
    case Qatar = 'qa';
    case Reunion = 're';
    case Romania = 'ro';
    case Serbia = 'rs';
    case Russia = 'ru';
    case Rwanda = 'rw';
    case SaudiArabia = 'sa';
    case SolomonIslands = 'sb';
    case Seychelles = 'sc';
    case Sudan = 'sd';
    case Sweden = 'se';
    case Singapore = 'sg';
    case AscensionIsland = 'sh-ac';
    case TristanDaCunha = 'sh-hl';
    case SaintHelenaIsland = 'sh-ta';
    case SaintHelena = 'sh';
    case Slovenia = 'si';
    case SvalbardAndJanMayen = 'sj';
    case Slovakia = 'sk';
    case SierraLeone = 'sl';
    case SanMarino = 'sm';
    case Senegal = 'sn';
    case Somalia = 'so';
    case Suriname = 'sr';
    case SouthSudan = 'ss';
    case SaoTomeAndPrincipe = 'st';
    case ElSalvador = 'sv';
    case SintMaarten = 'sx';
    case Syria = 'sy';
    case Eswatini = 'sz';
    case TurksAndCaicosIslands = 'tc';
    case Chad = 'td';
    case FrenchSouthernTerritories = 'tf';
    case Togo = 'tg';
    case Thailand = 'th';
    case Tajikistan = 'tj';
    case Tokelau = 'tk';
    case EastTimor = 'tl';
    case Turkmenistan = 'tm';
    case Tunisia = 'tn';
    case Tonga = 'to';
    case Turkey = 'tr';
    case TrinidadAndTobago = 'tt';
    case Tuvalu = 'tv';
    case Taiwan = 'tw';
    case Tanzania = 'tz';
    case Ukraine = 'ua';
    case Uganda = 'ug';
    case UnitedStatesMinorOutlyingIslands = 'um';
    case UnitedNations = 'un';
    case UnitedStates = 'us';
    case Uruguay = 'uy';
    case Uzbekistan = 'uz';
    case VaticanCity = 'va';
    case SaintVincentAndTheGrenadines = 'vc';
    case Venezuela = 've';
    case BritishVirginIslands = 'vg';
    case UnitedStatesVirginIslands = 'vi';
    case Vietnam = 'vn';
    case Vanuatu = 'vu';
    case WallisAndFutuna = 'wf';
    case Samoa = 'ws';
    case Kosovo = 'xk';
    case Unknown = 'xx';
    case Yemen = 'ye';
    case Mayotte = 'yt';
    case SouthAfrica = 'za';
    case Zambia = 'zm';
    case Zimbabwe = 'zw';

    public function label(): string
    {
        return match ($this) {
            self::Andorra => 'Andorra',
            self::UnitedArabEmirates => 'United Arab Emirates',
            self::Afghanistan => 'Afghanistan',
            self::AntiguaAndBarbuda => 'Antigua and Barbuda',
            self::Anguilla => 'Anguilla',
            self::Albania => 'Albania',
            self::Armenia => 'Armenia',
            self::Angola => 'Angola',
            self::Antarctica => 'Antarctica',
            self::Argentina => 'Argentina',
            self::ArabLeague => 'Arab League',
            self::AmericanSamoa => 'American Samoa',
            self::Asean => 'ASEAN',
            self::Austria => 'Austria',
            self::Australia => 'Australia',
            self::Aruba => 'Aruba',
            self::AlandIslands => 'Åland Islands',
            self::Azerbaijan => 'Azerbaijan',
            self::BosniaAndHerzegovina => 'Bosnia and Herzegovina',
            self::Barbados => 'Barbados',
            self::Bangladesh => 'Bangladesh',
            self::Belgium => 'Belgium',
            self::BurkinaFaso => 'Burkina Faso',
            self::Bulgaria => 'Bulgaria',
            self::Bahrain => 'Bahrain',
            self::Burundi => 'Burundi',
            self::Benin => 'Benin',
            self::SaintBarthelemy => 'Saint Barthélemy',
            self::Bermuda => 'Bermuda',
            self::Brunei => 'Brunei',
            self::Bolivia => 'Bolivia',
            self::CaribbeanNetherlands => 'Caribbean Netherlands',
            self::Brazil => 'Brazil',
            self::Bahamas => 'Bahamas',
            self::Bhutan => 'Bhutan',
            self::BouvetIsland => 'Bouvet Island',
            self::Botswana => 'Botswana',
            self::Belarus => 'Belarus',
            self::Belize => 'Belize',
            self::Canada => 'Canada',
            self::CocosIslands => 'Cocos (Keeling) Islands',
            self::CongoDemocraticRepublic => 'Democratic Republic of the Congo',
            self::CentralEuropeanFreeTradeAgreement => 'Central European Free Trade Agreement',
            self::CentralAfricanRepublic => 'Central African Republic',
            self::CongoRepublic => 'Republic of the Congo',
            self::Switzerland => 'Switzerland',
            self::IvoryCoast => 'Ivory Coast',
            self::CookIslands => 'Cook Islands',
            self::Chile => 'Chile',
            self::Cameroon => 'Cameroon',
            self::China => 'China',
            self::Colombia => 'Colombia',
            self::ClippertonIsland => 'Clipperton Island',
            self::CostaRica => 'Costa Rica',
            self::Cuba => 'Cuba',
            self::CapeVerde => 'Cape Verde',
            self::Curacao => 'Curaçao',
            self::ChristmasIsland => 'Christmas Island',
            self::Cyprus => 'Cyprus',
            self::CzechRepublic => 'Czech Republic',
            self::Germany => 'Germany',
            self::DiegoGarcia => 'Diego Garcia',
            self::Djibouti => 'Djibouti',
            self::Denmark => 'Denmark',
            self::Dominica => 'Dominica',
            self::DominicanRepublic => 'Dominican Republic',
            self::Algeria => 'Algeria',
            self::EastAfricanCommunity => 'East African Community',
            self::Ecuador => 'Ecuador',
            self::Estonia => 'Estonia',
            self::Egypt => 'Egypt',
            self::WesternSahara => 'Western Sahara',
            self::Eritrea => 'Eritrea',
            self::Catalonia => 'Catalonia',
            self::Galicia => 'Galicia',
            self::BasqueCountry => 'Basque Country',
            self::Spain => 'Spain',
            self::Ethiopia => 'Ethiopia',
            self::EuropeanUnion => 'European Union',
            self::Finland => 'Finland',
            self::Fiji => 'Fiji',
            self::FalklandIslands => 'Falkland Islands',
            self::Micronesia => 'Micronesia',
            self::FaroeIslands => 'Faroe Islands',
            self::France => 'France',
            self::Gabon => 'Gabon',
            self::England => 'England',
            self::NorthernIreland => 'Northern Ireland',
            self::Scotland => 'Scotland',
            self::Wales => 'Wales',
            self::UnitedKingdom => 'United Kingdom',
            self::Grenada => 'Grenada',
            self::Georgia => 'Georgia',
            self::FrenchGuiana => 'French Guiana',
            self::Guernsey => 'Guernsey',
            self::Ghana => 'Ghana',
            self::Gibraltar => 'Gibraltar',
            self::Greenland => 'Greenland',
            self::Gambia => 'Gambia',
            self::Guinea => 'Guinea',
            self::Guadeloupe => 'Guadeloupe',
            self::EquatorialGuinea => 'Equatorial Guinea',
            self::Greece => 'Greece',
            self::SouthGeorgiaAndSouthSandwichIslands => 'South Georgia and the South Sandwich Islands',
            self::Guatemala => 'Guatemala',
            self::Guam => 'Guam',
            self::GuineaBissau => 'Guinea-Bissau',
            self::Guyana => 'Guyana',
            self::HongKong => 'Hong Kong',
            self::HeardIslandAndMcDonaldIslands => 'Heard Island and McDonald Islands',
            self::Honduras => 'Honduras',
            self::Croatia => 'Croatia',
            self::Haiti => 'Haiti',
            self::Hungary => 'Hungary',
            self::CanaryIslands => 'Canary Islands',
            self::Indonesia => 'Indonesia',
            self::Ireland => 'Ireland',
            self::Israel => 'Israel',
            self::IsleOfMan => 'Isle of Man',
            self::India => 'India',
            self::BritishIndianOceanTerritory => 'British Indian Ocean Territory',
            self::Iraq => 'Iraq',
            self::Iran => 'Iran',
            self::Iceland => 'Iceland',
            self::Italy => 'Italy',
            self::Jersey => 'Jersey',
            self::Jamaica => 'Jamaica',
            self::Jordan => 'Jordan',
            self::Japan => 'Japan',
            self::Kenya => 'Kenya',
            self::Kyrgyzstan => 'Kyrgyzstan',
            self::Cambodia => 'Cambodia',
            self::Kiribati => 'Kiribati',
            self::Comoros => 'Comoros',
            self::SaintKittsAndNevis => 'Saint Kitts and Nevis',
            self::NorthKorea => 'North Korea',
            self::SouthKorea => 'South Korea',
            self::Kuwait => 'Kuwait',
            self::CaymanIslands => 'Cayman Islands',
            self::Kazakhstan => 'Kazakhstan',
            self::Laos => 'Laos',
            self::Lebanon => 'Lebanon',
            self::SaintLucia => 'Saint Lucia',
            self::Liechtenstein => 'Liechtenstein',
            self::SriLanka => 'Sri Lanka',
            self::Liberia => 'Liberia',
            self::Lesotho => 'Lesotho',
            self::Lithuania => 'Lithuania',
            self::Luxembourg => 'Luxembourg',
            self::Latvia => 'Latvia',
            self::Libya => 'Libya',
            self::Morocco => 'Morocco',
            self::Monaco => 'Monaco',
            self::Moldova => 'Moldova',
            self::Montenegro => 'Montenegro',
            self::SaintMartin => 'Saint Martin',
            self::Madagascar => 'Madagascar',
            self::MarshallIslands => 'Marshall Islands',
            self::NorthMacedonia => 'North Macedonia',
            self::Mali => 'Mali',
            self::Myanmar => 'Myanmar',
            self::Mongolia => 'Mongolia',
            self::Macau => 'Macau',
            self::NorthernMarianaIslands => 'Northern Mariana Islands',
            self::Martinique => 'Martinique',
            self::Mauritania => 'Mauritania',
            self::Montserrat => 'Montserrat',
            self::Malta => 'Malta',
            self::Mauritius => 'Mauritius',
            self::Maldives => 'Maldives',
            self::Malawi => 'Malawi',
            self::Mexico => 'Mexico',
            self::Malaysia => 'Malaysia',
            self::Mozambique => 'Mozambique',
            self::Namibia => 'Namibia',
            self::NewCaledonia => 'New Caledonia',
            self::Niger => 'Niger',
            self::NorfolkIsland => 'Norfolk Island',
            self::Nigeria => 'Nigeria',
            self::Nicaragua => 'Nicaragua',
            self::Netherlands => 'Netherlands',
            self::Norway => 'Norway',
            self::Nepal => 'Nepal',
            self::Nauru => 'Nauru',
            self::Niue => 'Niue',
            self::NewZealand => 'New Zealand',
            self::Oman => 'Oman',
            self::Panama => 'Panama',
            self::PacificIslandsForum => 'Pacific Islands Forum',
            self::Peru => 'Peru',
            self::FrenchPolynesia => 'French Polynesia',
            self::PapuaNewGuinea => 'Papua New Guinea',
            self::Philippines => 'Philippines',
            self::Pakistan => 'Pakistan',
            self::Poland => 'Poland',
            self::SaintPierreAndMiquelon => 'Saint Pierre and Miquelon',
            self::PitcairnIslands => 'Pitcairn Islands',
            self::PuertoRico => 'Puerto Rico',
            self::Palestine => 'Palestine',
            self::Portugal => 'Portugal',
            self::Palau => 'Palau',
            self::Paraguay => 'Paraguay',
            self::Qatar => 'Qatar',
            self::Reunion => 'Réunion',
            self::Romania => 'Romania',
            self::Serbia => 'Serbia',
            self::Russia => 'Russia',
            self::Rwanda => 'Rwanda',
            self::SaudiArabia => 'Saudi Arabia',
            self::SolomonIslands => 'Solomon Islands',
            self::Seychelles => 'Seychelles',
            self::Sudan => 'Sudan',
            self::Sweden => 'Sweden',
            self::Singapore => 'Singapore',
            self::AscensionIsland => 'Ascension Island',
            self::TristanDaCunha => 'Tristan da Cunha',
            self::SaintHelenaIsland => 'Saint Helena Island',
            self::SaintHelena => 'Saint Helena',
            self::Slovenia => 'Slovenia',
            self::SvalbardAndJanMayen => 'Svalbard and Jan Mayen',
            self::Slovakia => 'Slovakia',
            self::SierraLeone => 'Sierra Leone',
            self::SanMarino => 'San Marino',
            self::Senegal => 'Senegal',
            self::Somalia => 'Somalia',
            self::Suriname => 'Suriname',
            self::SouthSudan => 'South Sudan',
            self::SaoTomeAndPrincipe => 'São Tomé and Príncipe',
            self::ElSalvador => 'El Salvador',
            self::SintMaarten => 'Sint Maarten',
            self::Syria => 'Syria',
            self::Eswatini => 'Eswatini',
            self::TurksAndCaicosIslands => 'Turks and Caicos Islands',
            self::Chad => 'Chad',
            self::FrenchSouthernTerritories => 'French Southern Territories',
            self::Togo => 'Togo',
            self::Thailand => 'Thailand',
            self::Tajikistan => 'Tajikistan',
            self::Tokelau => 'Tokelau',
            self::EastTimor => 'East Timor',
            self::Turkmenistan => 'Turkmenistan',
            self::Tunisia => 'Tunisia',
            self::Tonga => 'Tonga',
            self::Turkey => 'Turkey',
            self::TrinidadAndTobago => 'Trinidad and Tobago',
            self::Tuvalu => 'Tuvalu',
            self::Taiwan => 'Taiwan',
            self::Tanzania => 'Tanzania',
            self::Ukraine => 'Ukraine',
            self::Uganda => 'Uganda',
            self::UnitedStatesMinorOutlyingIslands => 'United States Minor Outlying Islands',
            self::UnitedNations => 'United Nations',
            self::UnitedStates => 'United States',
            self::Uruguay => 'Uruguay',
            self::Uzbekistan => 'Uzbekistan',
            self::VaticanCity => 'Vatican City',
            self::SaintVincentAndTheGrenadines => 'Saint Vincent and the Grenadines',
            self::Venezuela => 'Venezuela',
            self::BritishVirginIslands => 'British Virgin Islands',
            self::UnitedStatesVirginIslands => 'United States Virgin Islands',
            self::Vietnam => 'Vietnam',
            self::Vanuatu => 'Vanuatu',
            self::WallisAndFutuna => 'Wallis and Futuna',
            self::Samoa => 'Samoa',
            self::Kosovo => 'Kosovo',
            self::Unknown => 'Unknown',
            self::Yemen => 'Yemen',
            self::Mayotte => 'Mayotte',
            self::SouthAfrica => 'South Africa',
            self::Zambia => 'Zambia',
            self::Zimbabwe => 'Zimbabwe',
        };
    }

    public function thumbnail(): string
    {
        return '/flags/1x1/'.$this->value.'.svg';
    }

    public function image(): string
    {
        return '/flags/4x3/'.$this->value.'.svg';
    }
}
